// Generated by CoffeeScript 2.2.4
(function() {
  var fs, http;

  http = require("http");

  fs = require("fs");

  http.createServer(function(req, res) {
    if (req.url === "/") {
      return fs.readFile("./titles.json", function(err, data) {
        var titles;
        if (err) {
          console.error(err);
          return res.end("Server Error");
        } else {
          titles = JSON.parse(data.toString());
          return fs.readFile("./template.html", function(err, data) {
            var html, tmpl;
            if (err) {
              console.error(err);
              return res.end("Server Error");
            } else {
              tmpl = data.toString();
              html = tmpl.replace('%', titles.join('</li><li>'));
              res.writeHead(200, {
                'Content-Type': 'text.html'
              });
              return res.end(html);
            }
          });
        }
      });
    }
  }).listen(8000, "127.0.0.1");

}).call(this);
